name: cyber_hack20
description: Flutter cyber hack20.
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  sliding_up_panel: ^1.0.2
  google_fonts: ^1.1.0
  audioplayers: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/bg/
    - assets/sounds/
    - assets/google_fonts/